// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "AudioCatalogDataAsset.generated.h"

class USoundBase;
class USoundClass;
class USoundAttenuation;

/**
 * One playable audio event. Gameplay code never names a sound asset directly:
 * it asks UAudioCatalogSubsystem for an event ID (e.g. "Dock.ClampEngage"),
 * and this entry says which sound plays and how. Swapping a generated sound
 * for a recorded one means changing one entry.
 */
USTRUCT(BlueprintType)
struct ADASTREA_API FAudioCatalogEntry
{
	GENERATED_BODY()

	/** The sound to play (usually a SoundWave under /Game/Audio/<Category>/SW_*). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	TSoftObjectPtr<USoundBase> Sound;

	/** Volume multiplier applied when the event plays. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio", meta = (ClampMin = "0.0"))
	float Volume = 1.0f;

	/** Pitch multiplier picked uniformly from [X, Y] each time the event plays. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	FVector2D PitchRange = FVector2D(1.0f, 1.0f);

	/** Sound class (mix bus). Applied as SoundClassOverride on spawned components. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	TSoftObjectPtr<USoundClass> SoundClass;

	/** Attenuation for 3D playback. Unset = the sound's own settings. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	TSoftObjectPtr<USoundAttenuation> Attenuation;

	/**
	 * Optional alternates (e.g. footsteps). When non-empty, each play picks uniformly
	 * among Sound and these, so repeated events don't sound identical.
	 */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	TArray<TSoftObjectPtr<USoundBase>> Variations;

	/** True for loops. Looping events must be played with SpawnEventAttached so they can be stopped. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	bool bLooping = false;
};

/**
 * Event ID -> sound mapping. The project's catalog lives at /Game/Audio/DA_AudioCatalog
 * and is generated by Tools/import_audio_assets.py from Assets/Audio/generated/audio_manifest.json.
 */
UCLASS(BlueprintType)
class ADASTREA_API UAudioCatalogDataAsset : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	/** Dotted event IDs (e.g. "Engine.Light.Low", "UI.Click") to their sounds. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Audio")
	TMap<FName, FAudioCatalogEntry> Entries;

	/** Returns the entry for EventId, or nullptr. */
	const FAudioCatalogEntry* FindEntry(FName EventId) const { return Entries.Find(EventId); }
};
